### ISSUE TITLE
Maintained ?

### ISSUE THREAD

**Issue by rgarrigue** [zwindler/ansible-module-clapi#3]
Hi

I'd just like to know if this is still used & maintained, and maybe if you intend to submit this to upstream, to be added to ansible officials modules ? 

Best regards,

**Comment by zwindler** [comment]
Hi,

My initial intention was to publish it to official modules yes, but as far as I know, there are not many users using it (I know of only one, my previous company).
Also, I know that I inspired people working with centreon to make their own version but from what I've seen their work seemed a little "behind" mine. https://github.com/guillaumewatteeux/ansible-centreon

If I'm wrong and people ask for help, I will maintain it. 

As for pushing it to Ansible official, there is still work to make something considered clean enough (I'd like to use new CLAPI REST API rather than CLAPI binary, which resides only on centreon servers). 

I'm willing to do the work only if this is useful for some people.

**Comment by rgarrigue** [comment]
Ok well, I'm gonna ask centreon's guys before coming back to you

Thanks for the intel

**Comment by da-friedl** [comment]
Hi, currently we want to manage our Centreon with Ansible. With google i came up here. My colleagues and me are fluent in python and also have a very good contact to Centreon. What do you think about to push this project?

Best regards from Munich,
Daniel

**Comment by edhil** [comment]
Actually I think that would be helpful for a lot of people. 
Without proper automation solution, I guess that people turn from Centreon to other monitoring solutions.

**Comment by zwindler** [comment]
Hello,

I've been in contact with the author of another Ansible module for centreon, guillaumewatteeux.
https://github.com/guillaumewatteeux/ansible-centreon

We exchanged a bit and it seems that his work is better in the technical sense as it uses centreon REST API through an nearly release python SDK instead of CLAPI. It didn't exist when I wrote my module. 
The code is much more clean because of this and adding features will be a lot easier.

Long story short, I think our best bet is to join efforts in https://github.com/guillaumewatteeux/ansible-centreon and DEPRECATE this module. That's what I was supposed to do 2 months ago ;-)

There is still some work to do on *ansible-centreon* though because there is some documentation to write and other things to do to before even considering to apply to Ansible official modules.

I'll try to put a tasks in the repository of guillaume (he gave me the rights) listing what needs to be done before we can submit it to Ansible community.

**Comment by da-friedl** [comment]
Hi,

great that you wrote back very quick!
From our point of view it's absolutelty no problem if we manage our Centreon using CLAPI or the REST API :-) ...the thing is: we need a working Ansible module. I will star guillaumewatteeux project and looking forward to get your mentioned task-list!
